### ISSUE TITLE
Unable to remove the load balancer from vm scale set

### ISSUE THREAD

**Issue by Saravanan-QWC** [Azure/vm-scale-sets#53]
I have a vm scale set connected with load balancer that I wanted to move to application gateway.
Therefore I tried to delete the load balancer and back-end pool. However I received the following error
`Failed to delete load balancer backend pool 'ProdWeb01-pool'. Error: Cannot remove backend address pool ProdWeb01-pool from load balancer since it is in use by virtual machine scale set /subscriptions/XXXXX-XXXX-XXXXXXX/resourceGroups/XXXXX/providers/Microsoft.Compute/virtualMachineScaleSets/ProdWeb0`

How to remove this load balancer from the resource group?

**Comment by gatneil** [comment]
Does this article help? https://docs.microsoft.com/en-us/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-upgrade-scale-set#examples

**Comment by Saravanan-QWC** [comment]
No, I re-created the entire setup for now. Thanks :)

**Comment by surendarkani** [comment]
the given article is not working

https://docs.microsoft.com/en-us/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-upgrade-scale-set#examples

**Comment by surendarkani** [comment]
i have found the reason, when removing the load balancer VMSS VMs are should up to date unless it will fail.

action :
1. go to VMSS
2. instances
3.click on upgrade
4. now try to delete the backend pool 
success!!!!!!

**Comment by AnkitPathak41** [comment]
I followed the same steps
 go to VMSS
instances
3.click on upgrade
now try to delete the backend pool
No success!!!!!!  for me It just keep giving the same error

**Comment by MiLtOnXeZaR** [comment]
I tried to delete a load balancer by `az cli`:

`az network lb delete -g <<RESOURCE_GROUP_NAME>> -n <<LB_NAME>>`

and then I got this error:

`Cannot delete load balancer /subscriptions/123abcde-1a12-1abc-a1ab-1234a1234ab1/resourceGroups/<<RESOURCE_GROUP_NAME>>/providers/Microsoft.Network/loadBalancers/<<LB_NAME>> since its child resources xxxxxx are in use by virtual machine scale set /subscriptions/123abcde-1a12-1abc-a1ab-1234a1234ab1/resourceGroups/<<RESOURCE_GROUP_NAME>>/providers/Microsoft.Compute/virtualMachineScaleSets/<<VMSS_NAME>>.`

So, as a previous comments recommend, I did this steps by `az cli`:

1. Remove load balancer associated with the VMSS:
`az vmss update --resource-group <<RESOURCE_GROUP_NAME>> --name <<VMSS_NAME>> --remove virtualMachineProfile.networkProfile.networkInterfaceConfigurations[0].ipConfigurations[0].loadBalancerBackendAddressPools 0`

2. Upgrade instances in the VMSS:
`az vmss update-instances --instance-ids "*" -n <<VMSS_NAME>> -g <<RESOURCE_GROUP_NAME>>`

3. Remove the load balancer:
`az network lb delete -g <<RESOURCE_GROUP_NAME>> -n <<LB_NAME>>`

I had success with this steps.

**Comment by mahauber** [comment]
Issue still persists as of today 06.11.2025

**Comment by DmarshalTU** [comment]
> Issue still persists as of today 06.11.2025

yes, from the portal you need to:

1. upgrade the vmss
2. inside the backend pool ip config remove the resource of the vmss
3. upgrade the machines one more time to get rid of the lb
4. done
