### ISSUE TITLE
[Request for help] Conditional ARM-template and low-priority vmss

### ISSUE THREAD

**Issue by ig-sinicyn** [Azure/vm-scale-sets#57]
We have a custom RM template that creates multiple vm scale sets. Part of them should be low-pri vmss but rest should be deployed as regular vmss. The low pri ones should have its eviction policy set to "Delete".

The issue is, the ARM template deployment fails with "Virtual Machine Scale Sets only support the evictionPolicy setting when the Scale Set is low priority." error

Corresponding part of template:

```
			"type": "Microsoft.Compute/virtualMachineScaleSets",
			"copy": {
				"name": "vmss",
				"count": "[length(variables('vmss'))]"
			},
			"name": "[variables('vmss')[copyIndex('vmss')].name]",
			"apiVersion": "2018-04-01",
			"properties": {
				"upgradePolicy": {
					"mode": "[variables('vmss')[copyIndex('vmss')].mode]"
				},
				"overprovision": false,
				"virtualMachineProfile": {	
					"priority": "[if(variables('vmss')[copyIndex('vmss')].lowPriority, 'Low', 'Regular')]",
					"evictionPolicy": "[if(variables('vmss')[copyIndex('vmss')].lowPriority, 'Delete', 'Deallocate')]",
					"storageProfile": { … },
					…
					},
			},
			...
```

AFAIK there is no way to add the "evictionPolicy" attribute conditionally. So, can the logic for ARM template ignore the "evictionPolicy": "Deallocate" for regular vmss?

UPD: the priority: Regular does not works too, if VM was created earlier. Deploy fails with
    "message": "The specified priority value 'Regular' cannot be applied to the VirtualMachineScaleSet 'MyVmss' since no priority was specified while originally creating the VirtualMachineScaleSet."

**Comment by gatneil** [comment]
Hey @ig-sinicyn! You actually can conditionally include/exclude properties from your template. It's a bit complicated, so I wrote up a blog post describing how to do it and similar scenarios: https://negatblog.wordpress.com/2018/06/27/conditionals-in-arm-templates/. Basically, though, you can define two variables, one called 'vmProfileLow' with the eviction policy specified, and another called 'vmProfileRegular' with the eviction policy not specified. You can then define  a variable called 'finalVmProfile' like: "finalVmProfile": "[variables(concat('vmProfile', parameters('lowPriority')))]" -> this "finalVmProfile" variable will take on the value of the variable that ends with the value specified in parameter 'lowPriority'. You can then use this variable as the value for your virtualMachineProfile.

Hope this helps! :)

-Neil

**Comment by ig-sinicyn** [comment]
@gatneil 

Thanks for the suggestion! Workaround from the post constructs a complex object and to passes it to the template as a replacement for the whole `virtualMachineProfile` section, right?

The sad part is the virtualMachineProfile section is large and our template uses copy[] to fill some subsections (virtualMachineProfile/osProfile/secrets as example). I'll look if there's a way to use copy in variables definition. If not - we'll need to find another way.

**Comment by gatneil** [comment]
@ig-sinicyn yeah, I'm not sure if copy can be used in the variables section (I doubt it can). 3 possibilities come to mind:

1) deploy the scale set in a sub-template. Use conditionals to select which template to deploy. One sub-template has eviction policy, the other doesn't.
2) I'm not sure if this would work, but maybe instead of defining two complex variables and selecting one, we could put the objects as the values of the if-conditional. Something like: "virtualMachineProfile": "[if(condition, {object-with-eviction-policy}, {object-without-eviction-policy})]". I'm not actually sure if this would work, but it might. It might also be a bit difficult to read depending on how it's formatted.
3) can we specify null for property values to indicate the lack of a value? I'm not sure at all if this would work, but it's probably worth a try; something like "evictionPolicy": "[if(condition, 'Deallocate', null)]"

**Comment by ig-sinicyn** [comment]
@gatneil 

Workaround with null value works,
```
	"virtualMachineProfile": {
		"priority": "[if(variables('vmss')[copyIndex('vmss')].lowPriority, 'Low', json('null'))]",
		"evictionPolicy": "[if(variables('vmss')[copyIndex('vmss')].lowPriority, 'Delete', json('null'))]",
```
Thanks a lot!

Should i close the issue?

**Comment by gatneil** [comment]
@ig-sinicyn glad it works! Closing the issue now :)
